spring:
  cloud:
    stream:
      source: notificationEventSupplier
      bindings:
        notificationEventSupplier-out-0:
          destination: notification-events
    loadbalancer:
      ribbon:
        enabled: false
    rabbit:
      bindings:
        processTxnRequest-out-0:
          producer:
            batchingEnabled: true
            batchSize: 500
            batchBufferLimit: 100000
            batchTimeout: 5000
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  application:
    name: public-service

logging:
  level:
    org:
      springframework:
        amqp: DEBUG

server:
  port: 0


eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
