spring:
  cloud:
    stream:
      source: subscriptionEventSupplier
      bindings:
        subscriptionEventSupplier-out-0:
          destination: notification-subscription
    loadbalancer:
      ribbon:
        enabled: false
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  application:
    name: public-service


security:
  oauth2:
    resource:
      token-info-uri: http://localhost:50911/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin

server:
  port: 0


eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
